### ISSUE TITLE
Can you please make a Video Tutorials on How using the server Script ?

### ISSUE THREAD

**Issue by ZaidSameer** [Sir-hennihau/Image-Uploader-in-React-Native#1]
## Hi, Thanks for this amazing app,
Can you please make a Video Tutorials on how using the server Script ?

**Comment by Sir-hennihau** [comment]
Hi,
sorry, I don't got time for a complete video tutorial now.

This is how it could look like on a live server. 
![next server upload scripts folder](https://user-images.githubusercontent.com/23266886/31945665-1ad5278a-b8d0-11e7-8606-0cb62a5213fe.PNG)

If you need help running a webserver, I recommend [this link. ](https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-16-04)

If you got the scripts uploaded and accessible on your server, then set the file permissions to 755 (I'm not entirely into security yet, but I'm sure there's room for improvement here.).

Then change the fetch URI's in your scripts according to your servers IP/ domain. Don't forget to properly set a "/uploads" directory.

If you need further help, please reply.
